/**
 * Fails if PoolAddress.POOL_INIT_CODE_HASH no longer matches the compiled Dex223Pool.
 *
 *   npx hardhat run scripts/check-pool-init-code-hash.ts
 *
 * Every periphery contract derives pool addresses with CREATE2 from this constant. Any change to
 * Dex223Pool.sol - or to its compiler settings, `debug.revertStrings` included - changes the pool
 * creation code and therefore the hash, and the constant has to be regenerated by hand.
 *
 * Forgetting is remarkably hard to diagnose: every derived address simply misses, so calls land on
 * an address with no code and the tests fail with `Transaction reverted without a reason string`.
 * Nothing in that output mentions the hash. It has already happened twice in this repo (#38, #44),
 * costing ~42 failing tests each time, which is why this check exists.
 */
import { artifacts } from 'hardhat'
import { keccak256 } from 'ethers'
import fs from 'fs'
import path from 'path'

const SOURCE = path.join(__dirname, '..', 'contracts', 'dex-periphery', 'base', 'PoolAddress.sol')

async function main() {
  const pool = await artifacts.readArtifact('Dex223Pool')
  const actual = keccak256(pool.bytecode)

  const src = fs.readFileSync(SOURCE, 'utf8')
  const found = src.match(/POOL_INIT_CODE_HASH\s*=\s*(0x[a-fA-F0-9]{64})/)
  if (!found) {
    console.error(`FAIL: could not find POOL_INIT_CODE_HASH in ${SOURCE}`)
    process.exitCode = 1
    return
  }
  const declared = found[1].toLowerCase()

  if (declared === actual) {
    console.log(`OK: POOL_INIT_CODE_HASH matches the compiled Dex223Pool.\n  ${actual}`)
    return
  }

  console.error('FAIL: POOL_INIT_CODE_HASH is stale. Every CREATE2-derived pool address will miss,')
  console.error('and the tests will revert without a reason string rather than naming this.\n')
  console.error(`  declared (PoolAddress.sol):  ${declared}`)
  console.error(`  actual   (Dex223Pool):       ${actual}\n`)
  console.error('Fix: replace the constant with the actual value above, then recompile.')
  process.exitCode = 1
}

main().catch((e) => { console.error(e); process.exitCode = 1 })
